env:
  global:
  - CC_TEST_REPORTER_ID=3171ba1ac7c8575efee03c1febc5b473a5c91fdac738f6a10ef9e7c94367c91f
language: ruby
rvm:
- 2.3
deploy:
  provider: rubygems
  api_key:
    secure: d2fb87j/FeKsYwLEVkKRKKSMn/ozbJ0iXNDD5AZaoYEFhAMP+HqZObKytxpEI+TJOEK3A/4to7gYpA4dDDo0a4fH6me+ZKktDkj1jByvREgdRjLbiJMDVrCVzAZW+/phJYXDMSbEGs5O6USLWuqqmy+R2ZIsjSfiPl1Iwn9VrkAl7jCkiUOCq2YzNSphlic1r9HD4A1V4IX8eRnKMmPMyyXrLPtNzQQvKT4G9w8EqYibpXRXc6DTHhhJC8WZd09S2n0LW5kIEh0VaQbaN00CLu9wVODJC/qkm39xJn/2Gr0z/3Jj0RlfLa7tIruEzgK0ZXTYGzfJE6bLgZw0Wx7fQ49Cd4aRehZ2c/gzX4/5FEp8EA5y2ZfOo1GNTi2L+23tvl3mnmpuYEHtYVSpAWzNI8t2bC/uqm5xkCGJTfA9a24xyzf+zNvTqnmB53BOVF79liCZeWIp9P/A1AOX92lysHE4SqE5o/JJ+DIdMH8OO3ih7UwsijGriCXgdULsiGNGYDv+O1HRey8TNUHAwfzw3TEMkFbN0ucYDcaSVNo3AQ5GpLzLmuIH9yN+XhSFFyL4OAn2MT4MqazLSjJIxVX8o3/B/jeBhABtNyR+tPg1TtOMX+CXXzUkJAZqDPuCsHVNfDATCzdvV+MhRB+1dh8/5nB3UVQGMoOELAiz/H613Bw=
  on:
    tags: true
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
